default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: hello_app.v2_development

test:
  <<: *default
  database: hello_app.v2_test

production:
  <<: *default
  database: hello_app.v2_production
  username: hello_app.v2
  password: <%= ENV['HELLO_DATABASE_PASSWORD'] %>
